(function($){$.docCookies={getItem:function(sKey){return decodeURIComponent(document.cookie.replace(new RegExp("(?:(?:^|.*;)\\s*"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=\\s*([^;]*).*$)|^.*$"),"$1"))||null;},setItem:function(sKey,sValue,vEnd,sPath,sDomain,bSecure){if(!sKey||/^(?:expires|max\-age|path|domain|secure)$/i.test(sKey)){return false;}
var sExpires="";if(vEnd){switch(vEnd.constructor){case Number:sExpires=vEnd===Infinity?"; expires=Fri, 31 Dec 9999 23:59:59 GMT":"; max-age="+vEnd;break;case String:sExpires="; expires="+vEnd;break;case Date:sExpires="; expires="+vEnd.toUTCString();break;}}
document.cookie=encodeURIComponent(sKey)+"="+encodeURIComponent(sValue)+sExpires+(sDomain?"; domain="+sDomain:"")+(sPath?"; path="+sPath:"")+(bSecure?"; secure":"");return true;},removeItem:function(sKey,sPath,sDomain){if(!sKey||!this.hasItem(sKey)){return false;}
document.cookie=encodeURIComponent(sKey)+"=; expires=Thu, 01 Jan 1970 00:00:00 GMT"+(sDomain?"; domain="+sDomain:"")+(sPath?"; path="+sPath:"");return true;},hasItem:function(sKey){return(new RegExp("(?:^|;\\s*)"+encodeURIComponent(sKey).replace(/[\-\.\+\*]/g,"\\$&")+"\\s*\\=")).test(document.cookie);},keys:function(){var aKeys=document.cookie.replace(/((?:^|\s*;)[^\=]+)(?=;|$)|^\s*|\s*(?:\=[^;]*)?(?:\1|$)/g,"").split(/\s*(?:\=[^;]*)?;\s*/);for(var nIdx=0;nIdx<aKeys.length;nIdx++){aKeys[nIdx]=decodeURIComponent(aKeys[nIdx]);}
return aKeys;}};$.fn.sliceQuerystring=function(url){var query;if(-1!==url.indexOf("?")){query=url.slice(url.indexOf("?"),(url.indexOf("#")!==-1)?(url.indexOf("#")):(url.length));}else{query='';}
return query;};$.fn.glueQuerystring=function(paramsObj){var params=paramsObj||{};var queryStr='';$.each(params,function(k,v){queryStr+=((''===queryStr?'':'&')+k+"="+v);});return queryStr;};$.fn.setQuerystring=function(url,queryString){var new_url=url;if(queryString){if(-1!==url.indexOf("?")&&-1!==url.indexOf("#")){new_url=url.replace(/\/?\?(.*)(#.*)/,'/?'+queryString+'$2');}else if(-1!==url.indexOf("?")){new_url=url.replace(/\/?\?(.*)/,'/?'+queryString);}else if(-1!==url.indexOf("#")){new_url=url.replace(/(\/?)(#.*)/,'/?'+queryString+'$2');}else{new_url=url.replace(/\/?$/,'')+'/?'+queryString;}}
return new_url;};$.fn.parseQuerystring=function(text){var nvpair={};var qs=text.replace(/^\?|\/$/g,'').replace(/\?/g,'&');var pairs=qs.split('&');var i,v;$.each(pairs,function(i,v){if(v){var pair=v.split('=');try{nvpair[pair[0]]=decodeURIComponent(pair[1]);}catch(URIError){nvpair[pair[0]]=pair[1];}}});return nvpair;};$.keys=function(object){var keys=[];$.each(object,function(key){keys.push(key);});return keys;};var readURLCampaign=function(obj){var params={};if(obj.URL){params=$.extend(params,$.fn.parseQuerystring($.fn.sliceQuerystring(obj.URL)));}
if((params.affid||params.aff_id||params.affiliate_id)&&(params.offid||params.offer_id)){if(params.aff_id){params.affid=params.aff_id;delete params.aff_id;}
if(params.affiliate_id){params.affid=params.affiliate_id;delete params.affiliate_id;}
if(params.offer_id){params.offid=params.offer_id;delete params.offer_id;}
if(params.aff_sub){params.affsub=params.aff_sub;delete params.aff_sub;}}
if(params.tap_a&&params.tap_s){params.affid=params.tap_a;delete params.tap_a;params.affsub=params.tap_s;delete params.tap_s;}
return params;};var _parseCookies=function(){var cookies={};$.each($.docCookies.keys(),function(key,value){cookies[value]=$.docCookies.getItem(value);});return cookies;};var _saveCookies=function(cookieObj){var savedCnt=0;$.each(cookieObj,function(key,value){$.docCookies.setItem(key,value,Infinity,'/','.cloudsigma.com');savedCnt++;});return savedCnt;};var _readPrefixedStorageObj=function(storageObject,matchStr,strip){storageObject=storageObject||{};var filteredData={};$.each($.keys(storageObject),function(i,key){if(key.match(new RegExp(matchStr))){var val;var keyStr;if(storageObject.getItem instanceof Function){val=storageObject.getItem(key);}else{val=storageObject[key];}
keyStr=(strip?key.replace(new RegExp(matchStr),''):key);try{filteredData[keyStr]=decodeURIComponent(val);}catch(URIError){filteredData[keyStr]=val;}}});return filteredData;};var _writePrefixedStorageObj=function(storageObjectParam,dataObj,prefix){var storageObject=storageObjectParam||{};var written_cnt=0;var data=dataObj||{};$.each(data,function(key,val){key=prefix+key.replace(new RegExp('^'+prefix),'');if(storageObject.setItem instanceof Function){storageObject.setItem(key,val);}else{storageObject[key]=val;}
written_cnt+=1;});return written_cnt;};var getCampaignAffiliateAndPromocode=function(readObj){return _readPrefixedStorageObj(readObj,'^promocode-|^affiliate-|^campaign-',true);};var saveParamsToLocalStorage=function(params,writeObj){_writePrefixedStorageObj(writeObj,_readPrefixedStorageObj(params,'(^promo)'),'promocode-');_writePrefixedStorageObj(writeObj,_readPrefixedStorageObj(params,'(^utm_)'),'campaign-');_writePrefixedStorageObj(writeObj,_readPrefixedStorageObj(params,'(^aff|^offid)'),'affiliate-');};function trackOutboundLink(link){var data={link:link.href,hasParams:false};if(link.href.indexOf('?')===-1){data.hasParams=false;}else{data.hasParams=true;var params=$.fn.parseQuerystring($.fn.sliceQuerystring(link.href));data=$.extend(data,params);}
try{mixpanel.track('Marketing outbound navigation',data);}catch(err){}
if(link.target&&'_blank'==link.target){setTimeout(function(){var win=window.open(link.href,'_blank');win.focus();},300);}else{setTimeout(function(){document.location.href=link.href;},300);}}
$(function(){var urlParams=readURLCampaign(document);var prefixedCampaignParamsObj={};try{saveParamsToLocalStorage(urlParams,prefixedCampaignParamsObj);_saveCookies(prefixedCampaignParamsObj);}catch(err){}
try{saveParamsToLocalStorage(urlParams,window.localStorage);}catch(err){}
var WebAppOutBoundLinks=$('a.gowebapp, a[href*=".cloudsigma.com/ui"], a[href*=".cloudsigma.com/trynow"], a[href*=".cloudsigma.com/docs"]');$.each(WebAppOutBoundLinks,function(idx,el){var href=$(el).attr('href');var hrefParams=$.fn.parseQuerystring($.fn.sliceQuerystring(href));var localStorageParams={};var cookieParams={};try{localStorageParams=getCampaignAffiliateAndPromocode(window.localStorage);}catch(err){}
try{cookieParams=getCampaignAffiliateAndPromocode(_parseCookies());}catch(err){}
var newParams=$.extend(localStorageParams,cookieParams,hrefParams);var queryStr=$.fn.glueQuerystring(newParams);href=$.fn.setQuerystring(href,queryStr);$(el).attr('href',href);});WebAppOutBoundLinks.on('click',function(e){e.preventDefault();trackOutboundLink(this);});});var url=document.location.href;if(url!==''){var data={url:url,hasParams:false};if(url.match(/^https?:\/\/w{0,3}\.?cloudsigma.com\/\W/)){data.hasParams=true;var params=readURLCampaign(document);data=$.extend(data,params);}else if(url.match(/^https?:\/\/w{0,3}\.?cloudsigma.com\/?$/)){data.hasParams=false;}
try{mixpanel.track('Marketing homepage hit',data);}catch(err){}}})(jQuery);